apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uk-cpf
spec:
  template:
    metadata:
      name: uk-cpf
      labels:
        app: uk-cpf
    spec:
      containers:
        - name: container-pod-uk-cpf
          image: ukstin/validar-cpf:latest
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: uk-cpf


# $ kubectl logs -l app=lable-pod-java # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-java